### ISSUE TITLE
UMBRELLA ISSUE: Migration of geocat-comp examples to this repository from geocat-examples

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#258]
Migration and adaptation of geocat-comp issues currently [housed in geocat-examples](https://geocat-examples.readthedocs.io/en/latest/gallery-geocat-comp/index.html)

- [ ] Example: [moc_globe_alt](https://geocat-examples.readthedocs.io/en/latest/gallery-geocat-comp/comp_only/moc_globe_atl_example.html#sphx-glr-gallery-geocat-comp-comp-only-moc-globe-atl-example-py) (#287)
- [ ] Update [migrated calendar_average](https://geocat-comp.readthedocs.io/en/stable/examples/calendar_average.html) (#287)
- [ ] Example: [climatology_average](https://geocat-examples.readthedocs.io/en/latest/gallery-geocat-comp/matplotlib/climatology_average_example.html#sphx-glr-gallery-geocat-comp-matplotlib-climatology-average-example-py)
- [x] Example: [fourier_filters](https://geocat-examples.readthedocs.io/en/latest/gallery-geocat-comp/matplotlib/fourier_filter_example.html#sphx-glr-gallery-geocat-comp-matplotlib-fourier-filter-example-py) (@pilotchute)
- [ ] Example: [linint2](https://geocat-examples.readthedocs.io/en/latest/gallery-geocat-comp/matplotlib/linint2_example.html#sphx-glr-gallery-geocat-comp-matplotlib-linint2-example-py)
- [ ] Example: [linint2pts](https://geocat-examples.readthedocs.io/en/latest/gallery-geocat-comp/matplotlib/linint2pts_example.html#sphx-glr-gallery-geocat-comp-matplotlib-linint2pts-example-py)

Suggested tasks for adaptation of geocat-comp documentation
- More descriptive title, tags to describe concepts illustrated
- Remove unnecessary geocat-viz bloat in examples with visualizations
- Break larger blocks apart and add more descriptive markdown blocks
- Add properly formatted markdown links to original NCL documentation AND add links to relevant geocat-comp documentation throughout

**Comment by kafitzgerald** [comment]
@anissa111 did you mention you were hoping for these to go to applications?  If so, I'd totally spaced this and figured I'd just confirm and document.

**Comment by jukent** [comment]
I think comp could have examples in its documentation as well, so I'm not sure if we want some of these in comp or application personally.

**Comment by kafitzgerald** [comment]
Sounds like applications is the call.
